# Generated by Django 3.0.2 on 2020-02-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200208_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=200),
        ),
    ]
